// Code generated by goctl. DO NOT EDIT!
// Source: check.proto

package server

import (
	"context"

	"multi_micro/rpc_two/internal/logic"
	"multi_micro/rpc_two/internal/svc"
	"multi_micro/rpc_two/rpc_two"
)

type CheckerServer struct {
	svcCtx *svc.ServiceContext
}

func NewCheckerServer(svcCtx *svc.ServiceContext) *CheckerServer {
	return &CheckerServer{
		svcCtx: svcCtx,
	}
}

func (s *CheckerServer) Check(ctx context.Context, in *rpc_two.CheckReq) (*rpc_two.CheckResp, error) {
	l := logic.NewCheckLogic(ctx, s.svcCtx)
	return l.Check(in)
}
