// Code generated by goctl. DO NOT EDIT!
// Source: check.proto

package checker

import (
	"context"

	"multi_micro/rpc_two/rpc_two"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	CheckReq  = rpc_two.CheckReq
	CheckResp = rpc_two.CheckResp

	Checker interface {
		Check(ctx context.Context, in *CheckReq) (*CheckResp, error)
	}

	defaultChecker struct {
		cli zrpc.Client
	}
)

func NewChecker(cli zrpc.Client) Checker {
	return &defaultChecker{
		cli: cli,
	}
}

func (m *defaultChecker) Check(ctx context.Context, in *CheckReq) (*CheckResp, error) {
	client := rpc_two.NewCheckerClient(m.cli.Conn())
	return client.Check(ctx, in)
}
