// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"` // TODO: add members here and delete this comment
}

type Response struct {
	Data string `json:"data"` // TODO: add members here and delete this comment
}
