// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"middle_demo/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddle},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/users/id/:name",
					Handler: handlerNameHandler(serverCtx),
				},
			}...,
		),
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/no_middle/id/:name",
				Handler: handlerNomiddleNameHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddle_2},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/middle_2/id/:name",
					Handler: handlerMiddle_2Handler(serverCtx),
				},
			}...,
		),
	)
}
