// Code generated by goctl. DO NOT EDIT!
// Source: message.proto

package server

import (
	"context"

	"micro_demo/message/internal/logic"
	"micro_demo/message/internal/svc"
	"micro_demo/message/message"
)

type MessageSvrServer struct {
	svcCtx *svc.ServiceContext
}

func NewMessageSvrServer(svcCtx *svc.ServiceContext) *MessageSvrServer {
	return &MessageSvrServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageSvrServer) GetMessage(ctx context.Context, in *message.MessageReq) (*message.MessageResp, error) {
	l := logic.NewGetMessageLogic(ctx, s.svcCtx)
	return l.GetMessage(in)
}
